# Generated by Django 4.1.2 on 2022-10-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_topic_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
    ]
