# Generated by Django 4.1.2 on 2022-10-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/assets/images.png', null=True, upload_to='static/assets/avatars/', verbose_name='profile picture'),
        ),
    ]
